name : Second Overflow 

on: 
  #  push : 
  #    branches : ["main"]

  #This is used for manual trigger
  workflow_dispatch:

jobs: 
   secondJobName:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, Mayank Here Again!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo This workflow have been created,
          echo by, using VS CODE.

